In [3]:
!pip install torch

    100% |████████████████████████████████| 27.2MB 966kB/s ta 0:00:011    52% |████████████████▊               | 14.2MB 2.4MB/s eta 0:00:06    87% |████████████████████████████    | 23.7MB 2.4MB/s eta 0:00:02


In [27]:
import torch
import numpy as np

In [11]:
v = torch.tensor([1,2,3,4,5,6]) #int tensor
print(v)
print(v.dtype)
print(v[0])
print(v[1])
print(v[2])
print(v[1:4])
print(v[1:])

tensor([1, 2, 3, 4, 5, 6])
torch.int64
tensor(1)
tensor(2)
tensor(3)
tensor([2, 3, 4])
tensor([2, 3, 4, 5, 6])


In [14]:
f = torch.FloatTensor([1,2,3,4,5,6]) # float tensor
print(f)
print(f.dtype)
print(f.size())
print(f.shape)

tensor([1., 2., 3., 4., 5., 6.])
torch.float32
torch.Size([6])
torch.Size([6])


In [18]:
v.view(6, 1) #reshape

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [19]:
v.view(3, 2) #reshape to new matrix

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [25]:
v.view(3,-1) # reshape in the lenght of the tensor

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [28]:
a = np.array([1,2,3,4,5])
tensor_cnv = torch.from_numpy(a) # conver numpy to tensro
print(tensor_cnv)
print(tensor_cnv.type())

tensor([1, 2, 3, 4, 5])
torch.LongTensor


In [31]:
numpy_cnv = tensor_cnv.numpy()
print(numpy_cnv)
print(type(numpy_cnv))

[1 2 3 4 5]
<class 'numpy.ndarray'>
