In [1]:
!pip install torch

In [2]:
import torch

In [3]:
one_d = torch.arange(0,9)
one_d

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
two_d = one_d.view(3,3)
two_d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [5]:
two_d.dim()

2

In [6]:
two_d[1, 2]

tensor(5)

In [10]:
x = torch.arange(18).view(3,2,3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

In [11]:
x[1,1,1] # block, col, row

tensor(10)

In [13]:
x[1,0:2,1] # block, col, row

tensor([ 7, 10])

In [14]:
x[1,0:2,0:3] # block, col, row

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [15]:
x[1,:,:] # block, col, row

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])