In [2]:
!pip install torch

In [1]:
import torch
from torch.nn import Linear

In [3]:
torch.manual_seed(10) # consistent random values
model = Linear(in_features=1, out_features=1)
print(model.bias, model.weight) # y = weight*x + bias

Parameter containing:
tensor([-0.0343], requires_grad=True) Parameter containing:
tensor([[-0.0838]], requires_grad=True)


In [4]:
x = torch.tensor([2.0])
print(model(x))

tensor([-0.2019], grad_fn=<AddBackward0>)


In [5]:
x = torch.tensor([[2.0],[3.3]])
print(model(x))

tensor([[-0.2019],
        [-0.3109]], grad_fn=<AddmmBackward>)
