In [1]:
!pip install torch

In [2]:
import torch
import torch.nn as nn

In [3]:
class LR(nn.Module):
    def __init__(self, input_size, output_size):
        super().__init__();
        self.linear = nn.Linear(input_size, output_size);
        
    def forward(self, x):
        return self.linear(x)

In [4]:
torch.manual_seed(1) # consistent random values
module = LR(1,1)
print(list(module.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [5]:
x = torch.tensor([1.0]);
print(module.forward(x))

tensor([0.0739], grad_fn=<AddBackward0>)


In [6]:
x = torch.tensor([[1.0],[2.0]]);
print(module.forward(x))

tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward>)
